config/routes.rb
Rails.application.routes.draw do
  root 'application#home'

  get 'about' => 'application#about'
  get 'submit' => 'application#submit'
  get 'inspiration' => 'application#inspiration'
  get 'join' => 'application#join'

  # Auth/Authed Pages
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  get 'posts' => 'admin#posts'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

    def posts

    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    def home
    end

    def about
    end

    def submit
    end

    def inspiration
    end

    def join
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/dashboard.html.erb
<div class="dashboard">
    <div class="dashboard-nav">
        <a class="button new-post">
            <i class="icon-add"></i>
            Add Post
        </a>
    </div>

    <h4 class="list-header">
        <i class="icon-progress"></i>
        <span>In Progress</span>
        <span class="list-header-col">Status</span>
        <span class="list-header-col">By</span>
        <span class="list-header-col">Started On</span>
    </h4>

    <ul class="list progress-list">
        <li class="list-item">
            <a href="#">
                <span>Item 1 hahaha no waii</span>
            </a>
            <span class="list-item-col">Composing</span>
            <span class="list-item-col">Leo DaVinci</span>
            <span class="list-item-col">09-13-2015</span>
        </li>
        <li class="list-item">
            <a href="#">
                <span>Item 1 hahaha no waii</span>
            </a>
            <span class="list-item-col">Composing</span>
            <span class="list-item-col">Leo DaVinci</span>
            <span class="list-item-col">09-13-2015</span>
        </li>
    </ul>

    <h4 class="list-header">
        <i class="icon-published"></i>
        <span>Published</span>
        <span class="list-header-col">Status</span>
        <span class="list-header-col">By</span>
        <span class="list-header-col">Started On</span>
    </h4>

    <ul class="list progress-list">
        <li class="list-item">
            <a href="#">
                <span>Item 1 hahaha no waii</span>
            </a>
            <span class="list-item-col">Composing</span>
            <span class="list-item-col">Leo DaVinci</span>
            <span class="list-item-col">09-13-2015</span>
        </li>
        <li class="list-item">
            <a href="#">
                <span>Item 1 hahaha no waii</span>
            </a>
            <span class="list-item-col">Composing</span>
            <span class="list-item-col">Leo DaVinci</span>
            <span class="list-item-col">09-13-2015</span>
        </li>
    </ul>
</div>

app/views/admin/posts.html.erb
<div class="dashboard">
    <div class="dashboard-nav">
        <h4 class="dashboard-nav-header">Posts</h4>
        <a class="button new-post">
            <i class="icon-add"></i>
            Add Post
        </a>
    </div>

    <h4 class="list-header">
        <i class="icon-progress"></i>
        <span>In Progress</span>
        <span class="list-header-col">Status</span>
        <span class="list-header-col">By</span>
        <span class="list-header-col">Started On</span>
    </h4>

    <ul class="list progress-list">
        <li class="list-item">
            <a href="#">
                <span>Item 1 hahaha no waii</span>
            </a>
            <span class="list-item-col">Composing</span>
            <span class="list-item-col">Leo DaVinci</span>
            <span class="list-item-col">09-13-2015</span>
        </li>
        <li class="list-item">
            <a href="#">
                <span>Item 1 hahaha no waii</span>
            </a>
            <span class="list-item-col">Composing</span>
            <span class="list-item-col">Leo DaVinci</span>
            <span class="list-item-col">09-13-2015</span>
        </li>
    </ul>

    <h4 class="list-header">
        <i class="icon-published"></i>
        <span>Published</span>
        <span class="list-header-col">Status</span>
        <span class="list-header-col">By</span>
        <span class="list-header-col">Started On</span>
    </h4>

    <ul class="list progress-list">
        <li class="list-item">
            <a href="#">
                <span>Item 1 hahaha no waii</span>
            </a>
            <span class="list-item-col">Composing</span>
            <span class="list-item-col">Leo DaVinci</span>
            <span class="list-item-col">09-13-2015</span>
        </li>
        <li class="list-item">
            <a href="#">
                <span>Item 1 hahaha no waii</span>
            </a>
            <span class="list-item-col">Composing</span>
            <span class="list-item-col">Leo DaVinci</span>
            <span class="list-item-col">09-13-2015</span>
        </li>
    </ul>
</div>

app/views/application/about.html.erb
<div class="home-banner">
    <img id="logo" src="<%= asset_path('logo.png')%>"/>
</div>

<div id="about" class="home-content">
    <h2 class="centered-header">About YOTR</h2>

    <p>
        On April 12, 2015, a young black man named <a href="https://en.wikipedia.org/wiki/Death_of_Freddie_Gray" target="_blank">
        Freddie Gray</a> was arrested by the Baltimore City Police. Seven days later, Gray was pronounced dead due to
        injuries to his spinal cord. The city of Baltimore finally erupted after years and years of injustice. Its citizens
        rallied in the streets and organized events for local people to talk about the continued oppression that they
        faced in their city and in their country. The youth in particular, after years of feeling invisible, could no
        longer remain comfortable in their silence. Even though multiple people tried to force them into silence, these
        young people could not be stopped. Unfortunately, many of their messages are still going unheard by those
        outside of their communities, and the same injustices they are highlights are also continuing to occur all over
        the US.
    </p>
    <p>
        The purpose of this website is to make sure that voices of our youth - of our future - are heard. These young
        men and women know way more than they are given credit for and are more capable of changing the world than one
        can imagine. But in order for that to happen, we need to take some time to listen to these Youth on the Rise.
    </p>
</div>

app/views/application/home.html.erb
<div class="home-banner">
    <img id="logo" src="<%= asset_path('logo.png')%>"/>
</div>

<div id="read" class="home-content">
    <ul class="posts">
        <li class="post">
            <h2 class="post-title">This is the Post Title.</h2>
            <p class="post-byline">By: <a href="#">George Simmons</a></p>
            <p class="post-created">on Nov. 8, 2015</p>
            <div class="post-body">
                <p>
                    Phasellus at suscipit urna, id ultricies justo. Suspendisse quis justo mauris. In rhoncus viverra augue, id
                    posuere nibh bibendum ornare. Maecenas at sapien sapien. Nam imperdiet ultricies metus vel eleifend. Sed
                    ultrices metus ut lacinia gravida. Nam ut sem eu sem egestas ornare vel suscipit elit. Integer vel posuere
                    lacus. Fusce malesuada leo a mi tempor pellentesque. Donec malesuada, ex eu congue sodales, mi justo rhoncus
                    dolor, in tempus est arcu pretium ligula. Phasellus dui quam, faucibus sed rutrum id, varius sit amet lacus.
                </p>
            </div>
            <div class="post-footer">
                <a href="#">SHARE</a>
            </div>
        </li>
        <img class="post-separator" src="<%= asset_path('post_separator.png') %>"/>
        <li class="post">
            <h2 class="post-title">This is the Post Title.</h2>
            <p class="post-byline">By: <a href="#">George Simmons</a></p>
            <p class="post-created">on Nov. 8, 2015</p>
            <div class="post-body">
                <p>
                    Phasellus at suscipit urna, id ultricies justo. Suspendisse quis justo mauris. In rhoncus viverra augue, id
                    posuere nibh bibendum ornare. Maecenas at sapien sapien. Nam imperdiet ultricies metus vel eleifend. Sed
                    ultrices metus ut lacinia gravida. Nam ut sem eu sem egestas ornare vel suscipit elit. Integer vel posuere
                    lacus. Fusce malesuada leo a mi tempor pellentesque. Donec malesuada, ex eu congue sodales, mi justo rhoncus
                    dolor, in tempus est arcu pretium ligula. Phasellus dui quam, faucibus sed rutrum id, varius sit amet lacus.
                </p>
            </div>
            <div class="post-footer">
                <a href="#">SHARE</a>
            </div>
        </li>
    </ul>
</div>

app/views/application/inspiration.html.erb
<div class="home-banner">
    <img id="logo" src="<%= asset_path('logo.png')%>"/>
</div>

<div id="about" class="home-content">
    <h2 class="centered-header">Our Inspiration</h2>

    <p>Suggested reading/users from teachers.</p>
</div>

app/views/application/join.html.erb
<div class="home-banner">
    <img id="logo" src="<%= asset_path('logo.png')%>"/>
</div>

<div id="about" class="home-content">
    <h2 class="centered-header">Join Us</h2>

    <p>Lesson plans on how to start a YOTR or just a contact form to put others in touch with Allison.</p>
</div>

app/views/application/new_post.html.erb
<div class="home-banner">
    <img id="logo" src="<%= asset_path('logo.png')%>"/>
</div>

<div id="about" class="home-content">
    <h2>Here's where people submit their story:</h2>

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent malesuada efficitur dignissim. Aenean non sem ac risus tempus ornare ut a tellus. Curabitur tempus, turpis ac porta convallis, risus nisl hendrerit ipsum, id aliquam velit lacus eget nulla. In ut tellus sem. Nam eget erat purus. In sollicitudin nec turpis ut laoreet. Vivamus porta tortor sed urna aliquet efficitur.</p>
</div>

app/views/application/submit.html.erb
<div class="home-banner">
    <img id="logo" src="<%= asset_path('logo.png')%>"/>
</div>

<div id="about" class="home-content">
    <h2 class="centered-header">Submit your work</h2>

    <p>Full form to accept Name + Location and Audio, Video, Photo, Text & Links.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Youth on the Rise</title>

        <!-- Meta -->
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="<%= image_path('favicon.png')%>" rel="icon" type="img/png"></link>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body class="js-body">
        <div class="header js-header">
            <nav id="topnav">
                <% if params[:controller] != 'admin' %>
                    <li><a href="<%= root_path %>">READ</a></li>
                    <li><a href="<%= about_path %>">ABOUT</a></li>
                    <li><a href="<%= inspiration_path %>">INSPIRATION</a></li>
                    <li><a href="<%= join_path %>">JOIN US</a></li>
                    <li><a href="<%= submit_path %>">SUBMIT</a></li>
                    <% if user_signed_in? %>
                        <li class="account-links"><a href="<%= posts_path %>">ADMIN</a></li>
                        <li class="account-links"><%= link_to "LOGOUT", destroy_user_session_path, method: :delete %></li>
                    <% else %>
                        <li><a href="<%= new_user_session_path %>">LOGIN</a></li>
                    <% end %>
                <% else %>
                    <% if user_signed_in? %>
                        <li><a href="<%= root_path %>">SITE</a></li>
                        <li><a href="<%= posts_path %>">POSTS</a></li>
                        <li><a class="disabled" href="#">LESSONS</a></li>
                        <li><a class="disabled" href="#">RESOURCES</a></li>
                        <li class="account-links"><%= link_to "LOGOUT", destroy_user_session_path, method: :delete %></li>
                    <% end %>
                <% end %>
            </nav>

            <% if notice %>
                <p class="notice js-notice">
                    <%= notice %>
                    <i class="icon-cross js-close"></i>
                </p>
            <% end %>
            <% if alert %>
                <p class="alert js-notice">
                    <%= alert %>
                    <i class="icon-cross js-close"></i>
                </p>
            <% end %>

            <a href="#" class="show-menu js-show-menu">
                <i class="icon-menu"></i>
            </a>

            <nav id="menu" class="js-menu">
                <li class="menu-header">
                    <i class="icon-close js-close-menu"></i>
                    Menu
                </li>
                <li><a href="<%= root_path %>">HOME</a></li>
                <li><a href="<%= about_path %>">ABOUT</a></li>
                <li><a href="<%= inspiration_path %>">INSPIRATION</a></li>
                <li><a href="<%= join_path %>">JOIN US</a></li>
                <li><a href="<%= submit_path %>">SUBMIT</a></li>
                <li class="divider"></li>
                <% if user_signed_in? %>
                    <li><a href="<%= posts_path %>">POSTS</a></li>
                    <li><a href="<%=  %>">ADD POST</a></li>
                    <li><%= link_to "LOGOUT", destroy_user_session_path, method: :delete %></li>
                <% else %>
                    <li><a href="<%= new_user_session_path %>">LOGIN</a></li>
                    <li><a href="<%= new_user_registration_path %>">SIGN UP</a></li>
                <% end %>
            </nav>
        </div>

        <%= yield %>
    </body>
</html>